### PR TITLE
Update readme to show scoped dependency

### PR DESCRIPTION
**Pull request by icyflame**
- This issue leads to compilation issues while running with Node 0.10 on Travis CI.

### CODE REVIEW

**Comment by icyflame** [comment]
@kevva As you can see above, even the Travis build has passed now! :smiley:

**Comment by kevva** [comment]
I rather set `npm` version in `package.json`. Preferably in the [df](https://github.com/sindresorhus/df) repo.

**Comment by icyflame** [comment]
Can you tell me how to do that? I tried setting the `npm` version inside `engines` in the `package.json` file of the `df` repository, and build my fork of it on Travis. But then, it still didn't work. Travis CI didn't change the npm version before building.

Is that the way it should be done?

**Comment by sindresorhus** [comment]
The engine field is not enforced, so that wouldn't help, unfortunately.

No way that every dependent should have to document this though. Being on the latest npm should a prerequisite always. You can easily upgrade npm in Travis for Node 0.10, Google it.

**Comment by icyflame** [comment]
@sindresorhus 

Yes, I do know how to update npm, and that's how I am managing my modules for now! But I thought it would be great to have a solution! Anyways, thanks!

**Comment by sindresorhus** [comment]
> But I thought it would be great to have a solution!

I just told you the solution. We can't magically fix a no longer updated ancient version of npm.

**Comment by icyflame** [comment]
@sindresorhus Yeah, I understand the solution, thank you. Sorry!

**Pull request closed without merging**
